### PR TITLE
Fix bug with add/set values for NumericalSampleBase class

### PR DESCRIPTION
**Pull request by pockerman**
Review implementation for sample view

### CODE REVIEW

**Review by jethronap — COMMENTED** [review]
I've reviewed the merged version. can you check it out?

**Comment by pockerman** [comment]
I did it

**Comment by jethronap** [comment]
do you think we merge now?

**Comment by pockerman** [comment]
Click on the commit messages above. I implemented your review findings. If you are satisfied we can merge it I believe....

**Review by jethronap — APPROVED** [review]
Ok, perfect!

**Comment by jethronap** [comment]
shall I delete this branch now? is it ok with you?

**Comment by pockerman** [comment]
yes if you merged it we can delete it

**Pull request merged**
